version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: estoque_postgres
    environment:
      POSTGRES_DB: estoque_db
      POSTGRES_USER: estoque_user
      POSTGRES_PASSWORD: estoque_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U estoque_user -d estoque_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - estoque_network
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: estoque_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - estoque_network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: estoque_kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - estoque_network
      - ecommerce-shared
    restart: unless-stopped

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: estoque_kafdrop
    restart: unless-stopped
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: 'kafka:9092'
      JVM_OPTS: '-Xms32M -Xmx64M'
      SERVER_PORT: '9000'
    depends_on:
      kafka:
        condition: service_started
    networks:
      - estoque_network
      - ecommerce-shared

  estoque_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque_app
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_NAME: estoque
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/estoque_db
      SPRING_DATASOURCE_USERNAME: estoque_user
      SPRING_DATASOURCE_PASSWORD: estoque_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - estoque_network
      - ecommerce-shared
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  estoque_network:
    driver: bridge
  ecommerce-shared:
    external: true
    name: ecommerce-shared-network 